version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
      POSTGRES_USER: chem
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db" ]
